name: Build APK Kasir

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Ekstrak ZIP
      run: unzip KasirIhsan_FINAL.zip
      
    - name: Build APK Pake Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        workdir: .
        buildozer_version: stable
        
    - name: Upload Hasil APK
      uses: actions/upload-artifact@v4
      with:
        name: APK-Kasir-Ihsan
        path: bin/*.apk
