name: Build APK Kasir
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Ekstrak ZIP
      run: unzip KasirIhsan_FINAL.zip
    - name: Build APK Pake Buildozer
      uses: nkiiiiid/buildozer-action@v1
      with:
        python-version: 3.10
        workdir: .
    - name: Upload Hasil APK
      uses: actions/upload-artifact@v4
      with:
        name: APK-Kasir-Ihsan
        path: bin/*.apk
