- name: Install Python 3.10
  uses: actions/setup-python@v5
- name: Install dependensi Ubuntu
  run: |
    sudo apt update
- name: Install Buildozer
  run: |
    pip install --upgrade Cython==0.29.33 buildozer
- name: Build APK
  run: buildozer android debug
